### ISSUE TITLE
question regarding safety filter

### ISSUE THREAD

**Issue by DarkReaperBoy** [PublicAffairs/openai-gemini#14]
So, with gemini's api, can disable certain safety filters, is it on this backend and if so, how to disable the filter?

**Comment by johnd0e** [comment]
Filter is already disabled:
https://github.com/PublicAffairs/openai-gemini/blob/c11d54b789a7cc150b7831eb40e15418704d0e00/src/worker.mjs#L120

See https://ai.google.dev/gemini-api/docs/safety-settings

**Comment by DarkReaperBoy** [comment]
weird as i find it stops streaming when it detects something inappropriate, thanks anyways :pray:
