### ISSUE TITLE
please support ask from files (images,media,pdf)

### ISSUE THREAD

**Issue by bugbounted** [PublicAffairs/openai-gemini#16]
hi [PublicAffairs](https://github.com/PublicAffairs)
please support ask from files (images,media,pdf) & put sample in readme.md
waiting for your repsonse
regards

**Comment by johnd0e** [comment]
Hi.
1. This projects contains no original api, so you'll need to search for [OpenAI](https://openai.com/api/) API examples.
   As mentioned here in _openai-gemini_ README, only the [`chat/completions`](https://platform.openai.com/docs/api-reference/chat/create) endpoint is supported: for the purposes _openai-gemini_ I can only support those API parts common to both OpenAI and Gemini.
3. Currently in the api there is direct support for [sending images](https://platform.openai.com/docs/api-reference/chat/create#chat-create-messages) only. There is no direct way for processing PDFs, though it is definitely possible at the application level (so the app may need to extract text or image data on its own).
4. This project is solely for API translation. You might be looking for a different type of software. There are many applications for interacting with documents. I'm not sure of your exact needs, but here's a random example: https://github.com/haruiz/geminiplayground. You can also search for "RAG" keyword.
