### ISSUE TITLE
The latest deployment version does not support the two parameters of "presence_penalty"&"frequency_penalty" for the model "gemini-exp-1206"

### ISSUE THREAD

**Issue by sam-lyu** [PublicAffairs/openai-gemini#27]
A 400 error will be returned specifically for the model **"gemini-exp-1206"**.
The flash model **"gemini-2.0-flash-exp"** is functioning correctly.
![Image](https://github.com/user-attachments/assets/45c5fa87-5bfb-43b3-9192-c690044fb95b)

**Comment by johnd0e** [comment]
Therefore, *penalty arguments are not supported for that model.
Unfortunately this is beyond our control.
