### ISSUE TITLE
some way to hide thinking in output of gemini-2.0-flash-thinking-exp

### ISSUE THREAD

**Issue by DarkReaperBoy** [PublicAffairs/openai-gemini#29]
as the title says, if it's not too much, i can bare with it though. because it filled context quick _and_ effects the model's behavior.

**Comment by johnd0e** [comment]
In principle, there are certain features that allow you to determine where reasoning ends and the final answer starts. However, these features are undocumented, which means Google could change the implementation at any time, so I wouldn't risk relying on them.

At the moment you can determine the start of the final response by the "|>" marker, so perhaps that will be enough for you.

**Comment by DarkReaperBoy** [comment]
thank you 🙏
