### ISSUE TITLE
部署后，在openai-translator使用出现“400 INVALID_ARGUMENT”错误。

### ISSUE THREAD

**Issue by crosspacific** [PublicAffairs/openai-gemini#3]
在cloudflare worker 部署后，在openai-translator 客户端使用出现“400 INVALID_ARGUMENT”。

![20240307202937](https://github.com/PublicAffairs/openai-gemini/assets/48462348/df0d17a2-030d-4cda-9906-88d7cbf328c7)

请问这是什么原因呢？谢谢。

**Comment by xingwozhonghua126** [comment]
你知道autogpt怎么用这个吗？openai_key怎么填写

**Comment by xingwozhonghua126** [comment]
> > 你知道autogpt怎么用这个吗？openai_key怎么填写
> 
> key 就是gemini的key。

我用autogpt,https://my-openai-gemini-demo.vercel.app/v1测试输入自己的key，不行，是必须要自己部署吗？我还不会部署。看你有打开了，就问问你

**Comment by crosspacific** [comment]
> 我用autogpt,[https://my-openai-gemini-demo.vercel.app/v1测试输入自己的key，不行，是必须要自己部署吗？我还不会部署。

key就是是Gemini的key， 完整的网址是https://my-openai-gemini-demo.vercel.app/v1/chat/completions，具体要看你软件的设置。 可能有些软件的支持也不太好。我在openai-translator 客户端使用，就会出现错误。

**Comment by johnd0e** [comment]
@crosspacific 
The reason of error is explained in error message.
It appears, that "OpenAI-Translator" uses some smart prompt, and the last message is on behalf of the model.
Unfortunately Gemini API does not support this.

BTW, I see that OpenAI-Translator should support Gemini natively, check this.

**Comment by crosspacific** [comment]
> @crosspacific
> 
> The reason of error is explained in error message. It appears, that "OpenAI-Translator" uses some smart prompt, and the last message is on behalf of the model. Unfortunately Gemini API does not support this.
> 
> BTW, I see that OpenAI-Translator should support Gemini natively, check this.

Thanks. This prompt works in OpenAI-Translator (v0.3.30), but not in the latest version (v0.3.33). Maybe the software has modified the prompt.

**Comment by Nicolaides648** [comment]
Hello, your other repository cannot be opened. I forgot to fork. I think this repository is very useful. Will you upload it again? Thank you.

**Comment by johnd0e** [comment]
@Nicolaides648 
If you are interested in `openai-github-copilot` then try on gitea.com
